/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary-container": "#4d3618",
        "secondary-container": "#c0ecda",
        "surface-container-low": "#eef5f7",
        "surface-variant": "#dde4e6",
        "tertiary-container": "#c09f78",
        "outline-variant": "#dec0ba",
        "on-surface": "#161d1f",
        "outline": "#8b716d",
        "inverse-on-surface": "#ebf2f4",
        "surface-tint": "#a53b29",
        "inverse-surface": "#2b3234",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#002117",
        "on-primary-fixed-variant": "#842415",
        "inverse-primary": "#ffb4a6",
        "surface": "#f4fafd",
        "secondary-fixed-dim": "#a5d0be",
        "secondary-fixed": "#c0ecda",
        "primary": "#a53b29",
        "background": "#f4fafd",
        "secondary": "#3e6658",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#264e41",
        "surface-bright": "#f4fafd",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#3f0300",
        "surface-dim": "#d4dbdd",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dde4e6",
        "on-surface-variant": "#57423e",
        "error": "#ba1a1a",
        "on-background": "#161d1f",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#ff7e67",
        "primary-fixed": "#ffdad4",
        "on-primary-container": "#731709",
        "surface-container": "#e8eff1",
        "tertiary-fixed": "#ffddb7",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb4a6",
        "on-secondary-container": "#446c5e",
        "on-tertiary-fixed-variant": "#5b4223",
        "surface-container-high": "#e2e9ec",
        "tertiary": "#745938",
        "tertiary-fixed-dim": "#e4c198"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "stack-md": "12px",
        "stack-lg": "24px",
        "gutter": "16px",
        "container-padding": "20px",
        "stack-sm": "4px"
      }
    },
  },
  plugins: [],
}
